# Generated by Django 4.0 on 2021-12-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_order_coustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_addres',
            field=models.CharField(default='', max_length=500),
        ),
    ]
