# Generated by Django 4.0 on 2021-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Realname', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('sEmail', models.EmailField(max_length=150)),
                ('sPassword', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Signupusers',
            },
        ),
    ]
