# Generated by Django 4.0 on 2021-12-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
