# Generated by Django 4.0 on 2022-01-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
