# Generated by Django 4.0 on 2022-01-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_rename_category_categories_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credentials',
        ),
    ]
