# Generated by Django 4.0 on 2022-01-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_delete_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
    ]
