# Generated by Django 4.0 on 2022-01-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_rename_category_categories_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
    ]
