# Generated by Django 4.0 on 2022-01-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customers1',
        ),
    ]
