# Generated by Django 4.0 on 2022-01-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_alter_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customers2',
        ),
    ]
